program: src/train.py
name: "Exp1: Eigenvalues"
method: grid
metric:
  name: eval/score_t+64
  goal: minimize
parameters:
  lambda_val:
    values: [0.36, 0.68, 0.84, 0.92, 0.96, 0.98, 0.99]
  structure:
    value: dense
  patch_size:
    value: 1
  dim_y:
    value: 2
  seed:
    values: [0, 1]
  lr:
    values: [0.001, 0.0003, 0.0001]
  steps:
    value: 10000
